apiVersion: apps/v1
kind: Deployment
metadata:
  name: redfish-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redfish-exporter
  template:
    metadata:
      labels:
        app: redfish-exporter
    spec:
      containers:
        - name: redfish-exporter
          image: ghcr.io/mahfudza/redfish_exporter:latest
          command:
            - /redfish_exporter
            - --config.file=/etc/exporter/redfish_exporter.yml
          ports:
            - containerPort: 9610
          volumeMounts:
            - name: config-volume
              mountPath: /etc/exporter
          securityContext:
            readOnlyRootFilesystem: true
            privileged: false
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      volumes:
        - name: config-volume
          secret:
            secretName: redfish-exporter-config
